/// <reference types="react" />
import * as React from 'react';
export interface IEnhancedSwitchProps {
    type?: string;
    name?: string;
    value?: string | string[] | number;
    onMouseUp?: React.MouseEventHandler<HTMLInputElement>;
    onMouseDown?: React.MouseEventHandler<HTMLInputElement>;
    onMouseLeave?: React.MouseEventHandler<HTMLInputElement>;
    onTouchStart?: React.TouchEventHandler<HTMLInputElement>;
    onTouchEnd?: React.TouchEventHandler<HTMLInputElement>;
    id?: string;
    className?: string;
    role?: string;
    inputType: string;
    checked?: boolean;
    defaultChecked?: boolean;
    label?: string;
    disabled?: boolean;
    indeterminate?: boolean;
    onChange?: (event: React.FormEvent<HTMLInputElement>, checked: boolean) => void;
    onBlur?: (event: React.FormEvent<HTMLInputElement>) => void;
    onFocus?: (event: React.FormEvent<HTMLInputElement>) => void;
    checkboxClass?: string;
    radioClass?: string;
    checkedClass?: string;
    checkedCheckboxClass?: string;
    checkedRadioClass?: string;
    uncheckedClass?: string;
    uncheckedCheckboxClass?: string;
    uncheckedRadioClass?: string;
    disabledClass?: string;
    disabledCheckboxClass?: string;
    disabledRadioClass?: string;
    enabledClass?: string;
    enabledCheckboxClass?: string;
    enabledRadioClass?: string;
    indeterminateClass?: string;
    indeterminateCheckboxClass?: string;
    indeterminateRadioClass?: string;
    determinateClass?: string;
    determinateCheckboxClass?: string;
    determinateRadioClass?: string;
    hoverClass?: string;
    focusClass?: string;
    activeClass?: string;
    labelHover?: boolean;
    labelHoverClass?: string;
    increaseArea?: string;
    cursor?: boolean;
    inheritClass?: boolean;
    inheritID?: boolean;
    aria?: boolean;
    insert?: string;
    children?: JSX.Element;
    labelClassName?: string;
}
export interface IEnhancedSwitchState {
    checked?: boolean;
    focused?: boolean;
    hovered?: boolean;
    active?: boolean;
}
declare class EnhancedSwitch extends React.Component<IEnhancedSwitchProps, IEnhancedSwitchState> {
    static defaultProps: {
        checkboxClass: string;
        radioClass: string;
        checkedClass: string;
        disabledClass: string;
        indeterminateClass: string;
        hoverClass: string;
        focusClass: string;
        activeClass: string;
        labelHover: boolean;
        labelHoverClass: string;
        increaseArea: string;
        cursor: boolean;
        inheritClass: boolean;
        inheritID: boolean;
        aria: boolean;
    };
    private _mobile;
    private readonly checkboxRef;
    private readonly inputContainerRef;
    constructor(props: IEnhancedSwitchProps);
    componentDidMount(): void;
    componentWillReceiveProps(nextProps: IEnhancedSwitchProps): void;
    componentDidUpdate(): void;
    getValue(): string;
    setSwitched(newCheckedValue: boolean): void;
    setChecked(newCheckedValue: boolean): void;
    setIndeterminate(): void;
    adjustStyle(): void;
    isChecked(): boolean;
    isSwitched(): boolean;
    private handleChange(e);
    private handleBlur(e);
    private handleFocus(e);
    private handleHelperClick(event);
    render(): JSX.Element;
}
export default EnhancedSwitch;
